server.port: 8081
server.ssl.enabled: false

# openvidu setting
OPENVIDU_URL: "http://localhost:8443/"

spring:
  data:
    redis:
      host: localhost
      port: 4000

logging:
  level:
    com.a702.sarkem: debug