server.port: 8081
server.ssl.enabled: true

# openvidu setting
OPENVIDU_URL: "https://localhost:8443/"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DB
    username: USERNAME
    password: PASSWORD
  data:
    redis:
      host: localhost
      port: 4000

logging:
  level:
    com.a702.sarkem: debug